#!/bin/bash

set -ouex pipefail

QUALIFIED_KERNEL=$(rpm -q --queryformat '%{VERSION}-%{RELEASE}.%{ARCH}\n' kernel-cachyos)

# Snapshot installed packages before nvidia install
rpm -qa --qf '%{NAME}\n' | sort > /tmp/pre-nvidia-pkgs.txt

# Install full NVIDIA stack from negativo17 repo
dnf5 install -y --setopt=tsflags=noscripts \
    dkms-nvidia \
    nvidia-driver \
    nvidia-driver-libs \
    nvidia-driver-libs.i686 \
    nvidia-driver-cuda \
    nvidia-driver-cuda-libs \
    nvidia-driver-cuda-libs.i686 \
    nvidia-settings \
    nvidia-modprobe \
    nvidia-persistenced \
    libva-nvidia-driver

# Blacklist nouveau so nvidia driver takes over on NVIDIA hardware
# (on AMD/Intel machines nouveau is not loaded anyway)
cat > /usr/lib/modprobe.d/blacklist-nouveau.conf << 'EOF'
blacklist nouveau
options nouveau modeset=0
EOF

# Record nvidia packages for protection
mkdir -p /usr/share/veloxos
{
    echo "# NVIDIA packages and all dependencies (generated by nvidia.sh)"
    rpm -qa --qf '%{NAME}\n' | sort | comm -13 /tmp/pre-nvidia-pkgs.txt -
} > /usr/share/veloxos/protected-packages.txt
rm -f /tmp/pre-nvidia-pkgs.txt
echo "Recorded $(wc -l < /usr/share/veloxos/protected-packages.txt) nvidia packages."

# Build DKMS module for the installed kernel
# Force ld.bfd — gold linker fails with NVIDIA's -r + --gc-sections combination
NVIDIA_VER=$(rpm -q --queryformat '%{VERSION}\n' dkms-nvidia)
LD=ld.bfd dkms install -m nvidia -v "${NVIDIA_VER}" -k "${QUALIFIED_KERNEL}" --force || {
    echo "DKMS build failed — make.log:"
    cat /var/lib/dkms/nvidia/${NVIDIA_VER}/build/make.log || true
    exit 1
}

# Services are enabled/disabled at first boot by gpu-detect.service
# based on detected hardware — do not enable here

# Generate module dependencies
depmod "${QUALIFIED_KERNEL}"

# Generate initramfs with nvidia module included so it is available at early boot
/usr/bin/dracut --no-hostonly --kver "${QUALIFIED_KERNEL}" --reproducible --zstd -v \
    --add ostree --add fido2 -f "/usr/lib/modules/${QUALIFIED_KERNEL}/initramfs.img"

chmod 0600 /usr/lib/modules/"${QUALIFIED_KERNEL}"/initramfs.img
